### ISSUE TITLE
Missing checkpoint?

### ISSUE THREAD

**Issue by nicolaus-huang** [nusnlp/greco#2]
Hi, I'm new to this topic, I found something wrong when running the scripts your provided

```
humor@Charon:~/greco$ python score_all.py --auto --data_dir data/conll-official/texts --output_path outputs/some_scores.json --model some --source_file data/conll-source.txt --batch_size 16
Traceback (most recent call last):
  File "/home/humor/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/home/humor/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/humor/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'checkpoints/some/grammer'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/humor/greco/score_all.py", line 98, in <module>
    main(args)
  File "/home/humor/greco/score_all.py", line 37, in main
    model = get_model(args)
  File "/home/humor/greco/models.py", line 875, in get_model
    model = SOME(model_args)
  File "/home/humor/greco/models.py", line 596, in __init__
    self.model_g = BertForSequenceClassification.from_pretrained(self.args.g_dir)
  File "/home/humor/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2899, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/humor/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'checkpoints/some/grammer'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

I think this should be a local folder with checkpoints, but after a quick search I didn't find it.

Could u please provide more info to run this if u can?

**Comment by nicolaus-huang** [comment]
Ahh my bad, just found that in README.
